### ISSUE TITLE
Testing with No DMABUF & TCP

### ISSUE THREAD

**Issue by aracno** [telescope-proj/lgproxy#4]
Hi,
Should i do special config to test telescope with no special hardware?
i am constantly getting "no route to host".
Using pop-os 22.04 (5.19.0-76051900-generic) as client
![image](https://user-images.githubusercontent.com/2394873/195982793-dfdb92d8-0d2d-4994-9309-fa61d56c4105.png)

Proxmox 7.2.11 (5.15.53-1-pve) as host
![image](https://user-images.githubusercontent.com/2394873/195983005-98caf4d9-9163-4e48-96f7-e8d240d800d7.png)

Thank you.

**Comment by aracno** [comment]
Should i change something in conf/linux/networks.conf?

**Comment by beanfacts** [comment]
Hi, could you let me know how you're connecting the two devices? For instance:

- Are they on the same subnet or are you trying to access them across networks/the public Internet?
- What network card are you using to connect the two?
- What software versions are you using on both sides and do they match (OS, Libfabric, Looking Glass, etc.)?
- Could you let me know the IP addresses? If they actually contain your public address, note this is not a supported configuration. Else, if it's within the RFC 1918 address space (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)
- Please attach full log details in your issue or send me the logs via email as follows:

Subject Line: [Telescope] lgproxy#4 Logs
And attach your logs.

Thanks

**Comment by aracno** [comment]
> Hi, could you let me know how you're connecting the two devices? For instance:
> 
> * Are they on the same subnet or are you trying to access them across networks/the public Internet?
> * What network card are you using to connect the two?
> * What software versions are you using on both sides and do they match (OS, Libfabric, Looking Glass, etc.)?
> * Could you let me know the IP addresses? If they actually contain your public address, note this is not a supported configuration. Else, if it's within the RFC 1918 address space (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)
> * Please attach full log details in your issue or send me the logs via email as follows:
> 
> Subject Line: [Telescope] lgproxy#4 Logs And attach your logs.
> 
> Thanks

Hi,
thanks a lot, your answer point me in the right direction. Libfabric packages were not same versions on host/client.
Just compile from github on both and it works.

The Host is using a VGPU-unlock Tesla P40 on Proxmox.
User experience using Parsec or Sunshine/Moolight is really good.
But with LG i am getting like 15UPS max (very choppy).
I use:
1x Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (host)
1x Qualcomm Atheros Killer E220x Gigabit Ethernet Controller (client)
This is what i should expect without RDMA capable hardware?

**Comment by beanfacts** [comment]
The bottleneck is your client NIC running at 1Gbps. We provide a calculator at the bottom of the page [here](https://telescope-proj.github.io/lgproxy/user/requirements.html).

14-15 UPS at 1080p corresponds to 950 Mbps, the expected performance of a Gigabit NIC.

With a 10Gbps NIC on both sides your performance would be much better, though you might still experience stuttering depending on a variety of factors out of our control when RDMA isn't active (driver, congestion (control), CPU load, etc).
