### ISSUE TITLE
avx(2) required?

### ISSUE THREAD

**Issue by efschu** [telescope-proj/lgproxy#7]
Hi,

first, thanks so much for the update.

I guess it needs a CPU with AVX, cause it runs on an AMD Ryzen 9 5950X, on a AMD Ryzen 7 5700G and an Intel i5 8250U, which all have AVX and AVX2.

But it does not run on an Pentium Gold G5400T, which does not have AVX(2).

Can it be disabled AVX on compile or do I need to upgrade to a CPU with AVX(2)?

**Comment by beanfacts** [comment]
Hi,
I just pushed a change that should disable AVX by default. Please let me know if it solves the issue.

**Comment by efschu** [comment]
It solved it.

Thnx so much
